# docker-compose.yml
version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    command: [ "npm", "start" ]
    restart: always
networks:
  default:
    external:
      name: db_scc_default
